Don't reject private network https connections
pinojs/pino-elasticsearch pull request #70
Opened 2020-12-08 12:16 UTC by xamgore

Kibana and ElasticSearch require https to be set up, even for private networks, but all connections got rejected.

2020-12-08 12:48 UTC, mcollina requested changes
Can you make that part of the `opts`?

2020-12-08 22:43 UTC, xamgore commented
And how to call the argument in CLI, `--rejectUnauthorized`?

2020-12-08 23:24 UTC, mcollina commented
yes exactly

2020-12-09 18:12 UTC, xamgore commented
Nailed it.

2020-12-10 20:14 UTC, delvedor approved these changes
LGTM

2020-12-11 23:42 UTC, mcollina approved these changes
lgtm

2020-12-11 23:42 UTC, merged