feat: enable to read config file
pinojs/pino-elasticsearch pull request #71
Opened 2021-02-11 16:52 UTC by henry039

enable CLI to read config file

Usage:

`node ./index.js | tee -a ./pino_log/http.log | jq -c 'del(.req.headers) | del(.http.response.headers) | del(.redact)' | pino-elasticsearch -r config.json`

2021-02-11 21:44 UTC, mcollina requested changes
Can you please add a unit test?

2021-02-12 11:43 UTC, henry039 commented
I am not sure how to add unit test for `cli.js`
Try to using `const { spawn } = require('child_process');`
but fail to mock lib module

2021-02-12 13:43 UTC, mcollina commented
Why would you need to mock lib?

2021-02-12 13:48 UTC, mcollina requested changes

2021-02-12 13:48 UTC, mcollina commented on cli.js
> +    const config = JSON.parse(fs.readFileSync(path.join(__dirname, flags['read-config']), 'utf-8'))
You need to use `process.cwd()` instead of `__dirname`.

2021-02-12 13:48 UTC, mcollina commented on cli.js
> +    const config = require(path.join(__dirname, flags['read-config']))
You need to use `process.cwd()` instead of `__dirname`.

2021-02-12 13:49 UTC, mcollina commented
don't worry about the tests, there are none for the CLI

2021-02-12 17:12 UTC, mcollina approved these changes
lgtm

2021-02-12 17:13 UTC, mcollina commented
Waiting for @delvedor (who works for Elastic)

2021-06-15 09:11 UTC, merged